PTSMS/PTSMS/Controllers/Scheduling/InstructorsController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using PTSMSBAL.Curriculum.References;
using PTSMSBAL.Logic.Enrollment.Operations;
using PTSMSDAL.Models.Enrollment.Operations;
using PTSMSDAL.Models.Scheduling.Relations;
using PTSMSBAL.Scheduling.Others;

namespace PTSMS.Controllers.Scheduling
{
    [PTSAuthorizeAttribute]
    public class InstructorsController : Controller
    {
        //private PTSContext db = new PTSContext();
        InstructorLogic instructorLogic = new InstructorLogic();
        PersonLogic personLogic = new PersonLogic();
        ProgramLogic programLogic = new ProgramLogic();

        // GET: Instructors
        public ActionResult Index()
        {
            var instructors = instructorLogic.List();
            return View(instructors);
        }

        // GET: Instructors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instructor instructor = instructorLogic.Details((Int32)id);
            if (instructor == null)
            {
                return HttpNotFound();
            }
            return View(instructor);
        }

        // GET: Instructors/Create
        public ActionResult Create()
        {
            var listQualificationType = instructorLogic.GetQulaificationType();

            ViewBag.PersonId = new SelectList((List<Person>)personLogic.List(), "PersonId", "CompanyId");

            QualificationModel objQualificationModel = new QualificationModel();

            List<SelectListItem> types = new List<SelectListItem>();
            foreach (var item in listQualificationType)
            {
                types.Add(new SelectListItem { Text = item.Type, Value = item.QualificationTypeId.ToString() });
            }

            objQualificationModel.QualificationTypes = types;

            return View(objQualificationModel);
        }

        [HttpPost]
        public ActionResult Create(FormCollection formCollection)
        {
            string QualTypes = Request.Form["QualificationTypes"];
            string[] QualificationTypes = QualTypes.Split(',');
            string personIds = Request.Form["PersonId"];
            string[] personIdArray = personIds.Split(',');

            foreach (var personId in personIdArray)
            {
                //Save to Instructor and Instructor Qualification
                Instructor instructor = new Instructor();
                List<InstructorQualification> instructorQualificationLst = new List<InstructorQualification>();

                //Assign Instructor Qualification
                foreach (var item in QualificationTypes)
                {
                    if (!(String.IsNullOrEmpty(item) || String.IsNullOrWhiteSpace(item)))
                    {
                        InstructorQualification instructorQualification = new InstructorQualification();
                        instructorQualification.QualificationTypeId = Convert.ToInt32(item);
                        instructorQualificationLst.Add(instructorQualification);
                    }
                }
                //Assign Instructor
                instructor.PersonId = Convert.ToInt32(personId);
                //call Save Function
                instructorLogic.Add(instructor, instructorQualificationLst);
            }
            return RedirectToAction("Index");
        }


        // GET: Instructors/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instructor instructor = instructorLogic.Details(id);
            if (instructor == null)
            {
                return HttpNotFound();
            }
            ViewBag.PersonId = new SelectList((List<Person>)personLogic.List(), "PersonId", "CompanyId", instructor.PersonId);
            ViewBag.ShortName = instructor.Person.ShortName;
            return View(instructor);
        }

        // POST: Instructors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InstructorId,PersonId,StartDate,EndDate,CreationDate,CreatedBy,RevisionDate,RevisedBy")] Instructor instructor)
        {
            Instructor inst = instructorLogic.Details(instructor.InstructorId);
            if (ModelState.IsValid)
            {
                Person person = inst.Person;
                person.ShortName = Request.Form["ShortName"].ToString();
                personLogic.Revise(person);
                instructorLogic.Revise(inst);
                return RedirectToAction("Index");
            }
            ViewBag.PersonId = new SelectList((List<Person>)personLogic.List(), "PersonId", "CompanyId", inst.PersonId);
            ViewBag.ShortName = inst.Person.ShortName;
            return View(instructor);
        }
        
        // GET: Instructors/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instructor instructor = instructorLogic.Details(id);
            if (instructor == null)
            {
                return HttpNotFound();
            }
            return View(instructor);
        }

        // POST: Instructors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            instructorLogic.Delete(id);
            return RedirectToAction("Index");
        }

        public class QualificationModel
        {
            public IList<SelectListItem> QualificationTypes { get; set; }
        }

    }


}

PTSMS/PTSMS/Views/Instructors/Create.cshtml
@model PTSMS.Controllers.Scheduling.InstructorsController.QualificationModel

@{
    ViewBag.Title = "Create";
    ViewBag.Name = "Create Instructor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/AdminLTE/plugins/select2/select2.css" rel="stylesheet" />

@section scripts
{
    <script src="~/Scripts/bootbox.min.js"></script>
    <script src="~/Content/AdminLTE/plugins/select2/select2.full.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {


            $('#dpdPersonId').select2();
            //$("#dpdAttenAbsentTrainee").select2();

            $('.chkclass').click(function () {

                var getchkid = $(this).attr('id');
                var isChecked = $('#' + getchkid).is(':checked');

                if ($('#' + getchkid).is(':checked') == true) {
                    $('#td' + $(this).val()).css("color", "white");
                    $('#td' + $(this).val()).css("background-color", "green");
                }
                else {
                    $('#td' + $(this).val()).css("color", "black");
                    $('#td' + $(this).val()).css("background-color", "white");
                }
            });


            $("#CreateInstructorForm").submit(function (event) {


                ///////////////////////////////////
                var typeListVal = "";
                //QualificationTypes

                $('input:checkbox:checked').each(function () {
                    typeListVal = typeListVal + "," + $(this).val();
                });
                $('#QualificationTypes').val(typeListVal);

                var $CreateInstructorFormInstance = $('#CreateInstructorForm');
                $CreateInstructorFormInstance.submit();               
                //var value = $('select#PersonId option:selected').val();

                //var value = $('#PersonId :selected').text();
                //$.ajax({
                //    type: "post",
                //    url: "/Instructors/Create",
                //    data: { QualificationTypes: typeListVal, personId: value },
                //    datatype: "json",
                //    traditional: true,
                //    success: function (data) {

                //        var selectedIds;
                //        for (var i = 0; i < data.success.length; i++) {
                //            if (selectedIds != undefined) {
                //                selectedIds = selectedIds + " " + data.success[i];
                //            }
                //            else {
                //                selectedIds = data.success[i];
                //            }
                //        }
                //    }
                //});

            });

        });
    </script>
}



@using System.Web.Mvc.Html
@using (Html.BeginForm("Create", "Instructors", FormMethod.Post, new { id = "CreateInstructorForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Instructor</label>
            <div class="col-md-4">
                @Html.DropDownList("PersonId", null, htmlAttributes: new { @class = "form-control select2", id = "dpdPersonId", name = "dpdPersonId", multiple = "multiple", Style = "width:100%" })
                @*@Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            
                <label class="control-label col-md-2">Type</label>
                <div class="col-md-4">
                    <div id="divCheckBox" style="height: 100px; overflow: auto;border:solid; width:150px;">
                        @foreach (var names in @Model.QualificationTypes)
                        {
                            var checkBoxId = "chk" + names.Value;
                            var tdId = "td" + names.Value;
                            <table width="100%">
                                <tr>
                                    <td width="20px">
                                        <input type="checkbox" id="@checkBoxId" class="chkclass" value="@names.Value" />
                                    </td>
                                    <td id="@tdId" width="100px">
                                        @names.Text
                                    </td>
                                </tr>

                            </table>

                        }
                    </div>  
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                @*<input type="submit" value="Create" class="btn btn-default" />*@
                <input type="submit" value="Save" id="btnSave" class="btn btn-success" />
            </div>
        </div>

        <div class="form-group hide">
            <div class="col-md-offset-2 col-md-4">
                <input type="text" name="QualificationTypes" id="QualificationTypes" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PTSMS/PTSMS/Views/Instructors/Delete.cshtml
@model PTSMSDAL.Models.Enrollment.Operations.Instructor

@{
    ViewBag.Title = "Delete";
    ViewBag.Name = "Are you sure you want to delete this?";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />

<div>
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.CompanyId)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-success" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PTSMS/PTSMS/Views/Instructors/Details.cshtml
@model PTSMSDAL.Models.Enrollment.Operations.Instructor

@{
    ViewBag.Title = "Details";
    ViewBag.Name = "Instructor Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div>
     
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.CompanyId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.InstructorId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PTSMS/PTSMS/Views/Instructors/Edit.cshtml
@model PTSMSDAL.Models.Enrollment.Operations.Instructor

@{
    ViewBag.Title = "Edit";
    ViewBag.Name = "Edit Instructor";
    Layout = "~/Views/Shared/_Layout.cshtml";
} 
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InstructorId)

        <div class="form-group">
            @Html.LabelFor(model => model.PersonId, "PersonId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("PersonId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Person.ShortName, "ShortName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
               
                @Html.TextBox("ShortName",null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Person.ShortName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PTSMS/PTSMS/Views/Instructors/Index.cshtml
@model IEnumerable<PTSMSDAL.Models.Enrollment.Operations.Instructor>

@{
    ViewBag.Title = "Index";
    ViewBag.Name = "Instructor List";
    ViewBag.TableId = "tblInstructor";
    ViewBag.DefualtSortingColumnIndex = 1;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table display dataTable" cellspacing="0" role="grid" width="100%" id="tblInstructor">
    <thead>
        <tr>
            <th>No.</th>           
            <th>
                @Html.DisplayNameFor(model => model.Person.CompanyId)
            </th>
            <th>
                Name
            </th>
            <th>
               Short Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Person.Position)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.Person.RegistrationDate)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
            foreach (var item in Model)
            {
                <tr role="row" class="odd">
                    <td>@(i++) </td>                    
                    <td>
                        @Html.DisplayFor(modelItem => item.Person.CompanyId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Person.FirstName) @Html.DisplayFor(modelItem => item.Person.MiddleName) @Html.DisplayFor(modelItem => item.Person.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Person.ShortName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Person.Position)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Person.RegistrationDate)
                    </td>
                                        
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.InstructorId }) |
                        @Html.ActionLink("Details", "Details", new { id = item.InstructorId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.InstructorId })
                    </td>
                </tr>
            }
        }
    </tbody>
</table>