PTSMS/PTSMS/Controllers/Scheduling/InstructorScheduleController.cs
using PTSMSBAL.Scheduling.Others;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PTSMS.Controllers.Scheduling
{
    public class InstructorScheduleController : Controller
    {
        [HttpGet]
        //[PTSAuthorizeAttribute]
        public ActionResult GroundClass()
        {
            if (TempData["ScheduleMessage"] != null)
            {
                ViewBag.ScheduleMessage = TempData["ScheduleMessage"];
                TempData["ScheduleMessage"] = null;
            }
            return View();
        }

        [HttpGet]
        //[PTSAuthorizeAttribute]
        public ActionResult Equipment()
        {
            if (TempData["FTDAndFlyingScheduleMessage"] != null)
            {
                ViewBag.FTDAndFlyingScheduleMessage = TempData["FTDAndFlyingScheduleMessage"];
                TempData["FTDAndFlyingScheduleMessage"] = null;
            }
            return View();
        }

        [HttpGet]
        public JsonResult GetGroundSchedulerResourceForInstructor()
        {
            SchedulerUtility schedulerUtility = new SchedulerUtility();

            string companyId = HttpContext.User.Identity.Name;

            var events = schedulerUtility.GetGroundSchedulerResourceForInstructor(companyId);

            var schedulerResourceList = new List<object>();

            foreach (var e in events)
            {
                schedulerResourceList.Add(new
                {
                    id = e.BatchId,
                    SerialNumber = e.SerialNumber,
                    BatchClassName = e.BatchClassName
                });
            }
            return Json(schedulerResourceList.ToArray(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CancelSchedule(FormCollection formCollection)
        {
            SchedulerUtility schedulerUtility = new SchedulerUtility();
            string reason = Request.Form["cancelReason"];
            string remark = Request.Form["cancelRemark"];
            string flyingAndFTDScheduleId = Request.Form["cancelFlyingAndScheduling"];
            string date = Request.Form["txtEditDate"];
            string batch = Request.Form["txtBatchIdCurrent"];
            string lessonType = Request.Form["txtLessonTypeCurrent"];
            if (!string.IsNullOrEmpty(batch))
            {
                int batchClassId = int.Parse(batch);
                TempData["BatchClassId"] = batchClassId;
            }
            if (!string.IsNullOrEmpty(lessonType))
                TempData["LessonType"] = lessonType;

            TempData["displayDate"] = date;
            if (schedulerUtility.CancelSchedule(reason, remark, flyingAndFTDScheduleId))
                TempData["FTDAndFlyingScheduleMessage"] = "Scheduled has been canceled";
            else
                TempData["FTDAndFlyingScheduleMessage"] = "Failed to cancel schedule";
            return RedirectToAction("Equipment");
        }
        [HttpGet]
        public JsonResult GetGroundScheduledEventForInstructor(string month, string year)
        {
            SchedulerUtility schedulerUtility = new SchedulerUtility();

            string companyId = HttpContext.User.Identity.Name;

            var events = schedulerUtility.GetScheduledEventForInstructor(companyId, month, year);

            var scheduledEventList = new List<object>();

            foreach (var e in events)
            {
                scheduledEventList.Add(
                    new
                    {
                        id = e.EventID,
                        resourceId = e.ResourceId,
                        title = e.Title,
                        description = e.Description,
                        start = e.EventStart.AddHours(3),
                        end = e.EventEnd.AddHours(3),
                        allDay = Convert.ToBoolean(e.IsAllDay),

                        moduleID = e.ModuleID,
                        moduleCode = e.ModuleCode,

                        courseID = e.CourseID,
                        courseCode = e.CourseCode,

                        batchID = e.BatchID,
                        batchClassName = e.BatchClassName
                    });
            }
            return Json(scheduledEventList.ToArray(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetSchedulerResourceForInstructor()
        {
            SchedulerUtility schedulerUtility = new SchedulerUtility();

            string companyId = HttpContext.User.Identity.Name;

            var events = schedulerUtility.GetSchedulerResourceForInstructor(companyId);

            var schedulerResourceList = new List<object>();

            foreach (var e in events)
            {
                schedulerResourceList.Add(
                    new
                    {
                        id = e.EquipmentId,
                        equipmentModel = e.EquipmentModel,
                        EquipmentName = e.EquipmentName,
                        WorkingHours = e.WorkingHours
                    });
            }
            return Json(schedulerResourceList.ToArray(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetFTDandFlyingScheduledEventForInstructor(string month, string year)
        {
            SchedulerUtility schedulerUtility = new SchedulerUtility();

            string companyId = HttpContext.User.Identity.Name;

            var events = schedulerUtility.GetFTDandFlyingScheduledEventForInstructor(companyId, month, year);

            var scheduledEventList = new List<object>();
            //{ id: '1', resourceId: 'b', start: TODAY + 'T02:00:00', end: TODAY + 'T05:00:00', title: 'DAN' },
            foreach (var e in events)
            {
                scheduledEventList.Add(
                    new
                    {
                        id = e.EventID,
                        resourceId = e.ResourceId,
                        title = e.Title,
                        description = e.Description,
                        start = e.EventStart.AddHours(3),
                        end = e.EventEnd.AddHours(3),
                        allDay = Convert.ToBoolean(e.IsAllDay)
                    });
            }
            return Json(scheduledEventList.ToArray(), JsonRequestBehavior.AllowGet);
        }
        /*Begin, methods for edit*/

    }
}

PTSMS/PTSMS/Controllers/Scheduling/InstructorSchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using PTSMSBAL.Curriculum.Operations;
using PTSMSBAL.Logic.Scheduling.Relations;
using PTSMSDAL.Models.Scheduling.Relations;
using PTSMSDAL.Models.Curriculum.Operations;
using PTSMSBAL.Logic.Enrollment.Operations;
using PTSMSDAL.Generic;
using PTSMSBAL.Curriculum.References;
using PTSMSDAL.Models.Curriculum.References;

namespace PTSMS.Controllers.Scheduling
{
    public class InstructorSchedulesController : Controller
    {
        ModuleInstructorScheduleLogic moduleInstructorScheduleLogic = new ModuleInstructorScheduleLogic();
        CourseLogic courseLogic = new CourseLogic();
        ModuleLogic moduleLogic = new ModuleLogic();
        ProgramLogic programLogic = new ProgramLogic();
        InstructorLogic instructorLogic = new InstructorLogic();
        ModuleInstructorScheduleLogic moduleInstroctorLogic = new ModuleInstructorScheduleLogic();

        // GET: InstructorSchedules
        public ActionResult Index()
        {
            var moduleInstructorSchedule = moduleInstructorScheduleLogic.ListAll();//db.ModuleInstructorSchedules.Include(i => i.Instructor).Include(i => i.Module).Include(i => i.Instructor.Person);

            if (TempData["InstructorModuleScheduleMessage"] != null)
            {
                ViewBag.InstructorModuleScheduleMessage = TempData["InstructorModuleScheduleMessage"];
                TempData["InstructorModuleScheduleMessage"] = null;
            }
            return View(moduleInstructorSchedule);
        }

        // GET: InstructorSchedules/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ModuleInstructorSchedule moduleInstructorSchedule = moduleInstructorScheduleLogic.Details((int)id);
            if (moduleInstructorSchedule == null)
            {
                return HttpNotFound();
            }
            return View(moduleInstructorSchedule);
        }

        // GET: InstructorSchedules/Create
        public ActionResult Create()
        {
            ViewBag.InstructorId = new SelectList(moduleInstructorScheduleLogic.GetInstructorsByQualification("Ground"), "InstructorId", "Instructor.Person.FirstName");

            ViewBag.CourseId = new SelectList((List<Course>)courseLogic.List(), "CourseId", "CourseCode");
            ViewBag.ProgramId = new SelectList((List<Program>)programLogic.List(), "ProgramId", "ProgramName");

            return View();
        }

        [HttpGet]
        public ActionResult FilteredListModules(string CourseId)
        {
            int courseId = Convert.ToInt32(CourseId);

            ViewBag.InstructorId = new SelectList(instructorLogic.List(), "InstructorId", "Person.CompanyId");

            ViewBag.CourseId = new SelectList((List<Course>)courseLogic.List(), "CourseId", "CourseCode");

            var listModules = courseLogic.ListModulesByCourseId(courseId);

            ModuleModel objModuleModel = new ModuleModel();

            List<SelectListItem> modules = new List<SelectListItem>();
            foreach (var item in listModules)
            {
                modules.Add(new SelectListItem { Text = item.ModuleCode + "(" + item.ModuleTitle + ")", Value = item.ModuleId.ToString() });
            }

            objModuleModel.Module = modules;
            //return View(objModuleModel);
            return View("Create", objModuleModel);
        }

        [HttpPost]
        public ActionResult CreateModuleInstructorSchedule()
        {
            string modules = Request.Form["SelectedModules"];
            string instructorId = Request.Form["InstructorId"];

            //Save to Instructor and Instructor Qualification
            //  List<InstructorSchedule> instructorScheduleLst = new List<InstructorSchedule>(); 
            ModuleLogic moduleLogic = new ModuleLogic();
            //Assign Instructor Qualification
            var instrctId = Convert.ToInt32(instructorId);
            var moduleId = 0;
            string message = "";
            string[] moduleArray = modules.Split('~');
            foreach (var module in moduleArray)
            {
                if (string.IsNullOrEmpty(module))
                    continue;

                moduleId = Convert.ToInt32(module);
                Module objModule = (Module)moduleLogic.Details(moduleId);

                ModuleInstructorSchedule moduleInstructorSchedule = new ModuleInstructorSchedule();
                moduleInstructorSchedule.ModuleId = (int)(objModule.RevisionGroupId == null ? objModule.ModuleId : objModule.RevisionGroupId);
                moduleInstructorSchedule.InstructorId = instrctId;

                //save
                var result = moduleInstroctorLogic.ListModuleInstructors(instrctId, moduleId);

                if (result.Count() == 0)
                {
                    moduleInstroctorLogic.Add(moduleInstructorSchedule);

                }
                else
                {
                    message = message + result.FirstOrDefault().Instructor.Person.FirstName + " is already assigned to " + result.FirstOrDefault().Module.ModuleTitle + ". ";
                }
            }
            if (message == "")
                message = "Module has assigned to instructor successfully.";
            TempData["InstructorModuleScheduleMessage"] = message;
            return RedirectToAction("Index");
        }

        [HttpGet]
        public JsonResult GetModuleByProgram(int programId, int instructorId)
        {
            List<SelectListItem> modules = new List<SelectListItem>();
            var moduleList = courseLogic.ListModulesByProgram(programId);
            var existingAssociation=moduleInstructorScheduleLogic.ListInstructorModuleAssociation(instructorId);

            foreach(var m in moduleList)
            {
                if (existingAssociation.Where(ea => ea.ModuleId.Equals(m.ModuleId)).Count() == 0)
                {
                    modules.Add(new SelectListItem { Text = m.ModuleCode + "(" + m.ModuleTitle + ")", Value = m.RevisionGroupId == null ? m.ModuleId.ToString() : m.RevisionGroupId.ToString() });
                }
            }

            return Json(new { resultData = modules, hasList = modules.Count() > 0 }, JsonRequestBehavior.AllowGet);
        }

        // GET: InstructorSchedules/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ModuleInstructorSchedule moduleInstructorSchedule = moduleInstroctorLogic.Details((int)id);
            if (moduleInstructorSchedule == null)
            {
                return HttpNotFound();
            }
            ViewBag.InstructorId = new SelectList(instructorLogic.List(), "InstructorId", "InstructorId", moduleInstructorSchedule.ModuleInstructorScheduleId);
            ViewBag.ModuleId = new SelectList((List<Module>)moduleLogic.List(), "ModuleId", "ModuleCode", moduleInstructorSchedule.ModuleId);
            //ViewBag.PreviousRevisionId = new SelectList(db.InstructorSchedules, "InstructorScheduleId", "Status", moduleInstructorSchedule.PreviousRevisionId);
            return View(moduleInstructorSchedule);
        }

        // POST: InstructorSchedules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ModuleInstructorSchedule instructorSchedule)
        {

            if (ModelState.IsValid)
            {
                moduleInstroctorLogic.Revise(instructorSchedule);
                return RedirectToAction("Index");
            }
            ViewBag.InstructorId = new SelectList(instructorLogic.List(), "InstructorId", "CreatedBy", instructorSchedule.InstructorId);
            ViewBag.ModuleId = new SelectList((List<Module>)moduleLogic.List(), "ModuleId", "ModuleCode", instructorSchedule.ModuleId);
            //ViewBag.PreviousRevisionId = new SelectList(db.ModuleInstructorSchedules, "InstructorScheduleId", "Status");
            return View(instructorSchedule);
        }

        // GET: InstructorSchedules/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ModuleInstructorSchedule moduleInstructorSchedule = (ModuleInstructorSchedule)moduleLogic.Details((int)id);
            if (moduleInstructorSchedule == null)
            {
                return HttpNotFound();
            }
            return View(moduleInstructorSchedule);
        }

        // POST: InstructorSchedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            moduleInstroctorLogic.Delete(id);
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}

        public class ModuleModel
        {
            public IList<SelectListItem> Module { get; set; }
        }
    }
}

PTSMS/PTSMS/Views/InstructorSchedules/Create.cshtml
@{
    ViewBag.Title = "Create";
    ViewBag.Name = "Create Instructor Module Schedules.";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section scripts
    {
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
 
    <script type="text/javascript">
        $(document).ready(function () {

           // window.asd = $('.ddlMultiSlectBox').SumoSelect({ csvDispCount: 4 });
            //alert('ddlMultiSlectBox');
            $(document).on("click", ".chkclass", function () {
                debugger;
                //$('.chkclass').click(function () {
                var getchkid = $(this).attr('id');
                var isChecked = $('#' + getchkid).is(':checked');

                if ($('#' + getchkid).is(':checked') == true) {
                    $('#td' + $(this).val()).css("color", "white");
                    $('#td' + $(this).val()).css("background-color", "green");
                    //$('#td' + $(this).val()).addClass("chkselected");
                }
                else {
                    $('#td' + $(this).val()).css("color", "black");
                    $('#td' + $(this).val()).css("background-color", "white");
                }
            });


            $(".InstructorScheduleContainer").on('click', "#btnSave", function () {

                ///////////////////////////////////
                var selectedItems='';

                $('input:checkbox:checked').each(function () {
                    selectedItems += $(this).attr('value') + "~";
                });

                $("#SelectedModules").val(selectedItems);

               $("#formSelection").submit();

            });

            $('body').on('change', "#CourseId", function () {

                //alert("1");
                var getListUrl = "";
                getListUrl = "/InstructorSchedules/FilteredListModules";

                var data = $("#CourseId").val();

                //
                $.ajax({
                    url: getListUrl,
                    type: 'GET',
                    data: { CourseId: data },
                    success: function (result) {
                        if (result.hasList) {
                            // alert('hasList');
                            //var selectOption = "";

                            //var option = '<option value="">--Please Select--</option>';
                            //SelectedList = $('#dpdSelectedExam').empty();
                            //SelectedList.append($('<option></option>').val(null).html(option));


                            //jQuery.each(result.resultData, function (index, item) {
                            //    SelectedList.append($('<option></option>').val(item.Id).html(item.Name));
                            //});

                        }
                        else {
                            bootbox.alert("There is no registered" + Selected);
                        }
                    },
                    error: function () {
                        //  bootbox.alert("Error has occured!!!.");
                    }
                });
                //////////
            });


            $('#ProgramId').on('change', function () {
                debugger;
                // var PhaseCourseId = $('#dpdAddPhaseCourses').val();

                var programId = $(this).val();
                var instructorId = $("#InstructorId").val();

                var Url = "/InstructorSchedules/GetModuleByProgram";
                var Data = {
                    'programId': programId,
                    'instructorId': instructorId
                };
                //  alert(phaseScheduleId);
                $.ajax({
                    url: Url,
                    type: 'GET',
                    data: Data,
                    success: function (result) {
                        debugger;
                        if (result.hasList) {
                                
                            var innerText = '<table class="table display dataTable no-footer"><tr><th></th></tr>';
                            jQuery.each(result.resultData, function (index, item) {

                                innerText += '<tr id="'+"td"+item.Value+'">';
                                innerText += '<td>';

                                innerText += 
                                    '<input type="checkbox" id=' + '"chb' + item.Value + '"' + ' class="chkclass" value="' + item.Value + '">' + item.Text + '</input>';

                                innerText += '</td>';
                                innerText += '</tr>';
                            });
                            innerText += '</table>';

                            $('#contentSection').html(innerText);
                        }
                        else {
                            $('#contentSection').html('<table><tr><th></th></tr></table>');
                        }
                    },
                    error: function () {
                        bootbox.alert("Error has occured!!!.");
                    }
                });

            });

            $('#ProgramId').change();

        });
    </script>


}

 <br />

@*@using (Html.BeginForm())
    {*@
@Html.AntiForgeryToken()

<div class="form-horizontal InstructorScheduleContainer">
     
    @*<div class="form-group row">
        @Html.LabelFor(model => model.InstructorId, "InstructorId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("ProgramId", null, htmlAttributes: new { @class = "form-control" })
            
        </div>
    </div>*@

    @*<div class="form-group ">
            <div class="col-md-2">
                @Html.DropDownListFor(model => model.Module, (IEnumerable<SelectListItem>)ViewBag.CourseId, "Select Course", htmlAttributes: new { id = "CourseId", name = "CourseCode", @class = "form-control" })
            </div>
        </div>

        <div class="form-group ">
            <div class="col-md-2">
                @Html.DropDownList("CourseId", (IEnumerable<SelectListItem>)ViewBag.CourseId, new { multiple = "multiple" })
               @Html.DropDownListFor(m => m.Module, new SelectList(Model.Module, "Value", "Text"), new { @multiple = "multiple", @placeholder = "Please select Module", @class = "ddlMultiSlectBox" })
            </div>
        </div>*@
    <form id="formSelection" method="post" action="@Url.Action("CreateModuleInstructorSchedule", "InstructorSchedules")">
        <input type="hidden" name="SelectedModules" id="SelectedModules" />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.InstructorId, "InstructorId", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-4">
                @Html.DropDownList("InstructorId", null, htmlAttributes: new { @class = "form-control" })
                <br />
                @Html.DropDownList("ProgramId", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="section" id="contentSection">
            @*<table class="table display dataTable no-footer">
                <tr>
                    <th></th>
                    <th>Modules</th>
                </tr>

                @foreach (var names in @Model.Module)
                {
                    var checkBoxId = "chk" + names.Value;
                    <tr>
                        <td>
                            <input type="checkbox" id="@checkBoxId" class="chkclass" value="@names.Value" />
                        </td>
                        <td>
                            @names.Text
                        </td>
                    </tr>
                }
            </table>*@
            @*
            <div class="form-group">
                <div class="col-md-4">
                    <div class="form-group">
                        <div id="divCheckBox" style="height: 400px; overflow: auto;border:solid; width:500px;">

                            @foreach (var names in @Model.Module)
                            {
                                var checkBoxId = "chk" + names.Value;
                                var tdId = "td" + names.Value;
                                <table>
                                    <tr>
                                        <td style="width:auto">
                                            <input type="checkbox" id="@checkBoxId" class="chkclass" value="@names.Value" />
                                        </td>
                                        <td id="@tdId" style="width:auto">
                                            @names.Text
                                        </td>
                                    </tr>

                                </table>

                            }

                        </div>

                    </div>

                </div>
            </div>
            *@
    </div>
</form>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <input type="button" value="Save" id="btnSave" class="btn btn-success" />
        </div>
    </div>
</div>
@*}*@

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PTSMS/PTSMS/Views/InstructorSchedules/Delete.cshtml
@model PTSMSDAL.Models.Scheduling.Relations.ModuleInstructorSchedule

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>InstructorSchedule</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Instructor.Person.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor.Person.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Module.ModuleCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Module.ModuleCode)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PTSMS/PTSMS/Views/InstructorSchedules/Details.cshtml
@model PTSMSDAL.Models.Scheduling.Relations.ModuleInstructorSchedule

@{
    ViewBag.Title = "Details";
    ViewBag.Name = "Module Instructor Schedule Details.";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div>
    <h4>InstructorSchedule</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Instructor.Person.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructor.Person.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Module.ModuleCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Module.ModuleCode)
        </dd>       
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ModuleInstructorScheduleId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PTSMS/PTSMS/Views/InstructorSchedules/Edit.cshtml
@model PTSMSDAL.Models.Scheduling.Relations.ModuleInstructorSchedule

@{
    ViewBag.Title = "Edit";
    ViewBag.Name = "Edit Module Instructor Schedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ModuleInstructorScheduleId)

        <div class="form-group">
            @Html.LabelFor(model => model.ModuleInstructorScheduleId, "ModuleInstructorScheduleId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("InstructorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModuleInstructorScheduleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModuleId, "ModuleId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("ModuleId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModuleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>