PTSMS/PTSMS/Controllers/Scheduling/FlightLogsController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using System.Web.Mvc;
using PTSMSDAL.Context;
using PTSMSDAL.Models.Scheduling.Relations;
using PTSMSBAL.Scheduling.Operations;
using PTSMSBAL.Scheduling.Relations;
using PTSMSDAL.Models.Dispatch;
using PTSMSBAL.Dispatch;
using PTSMSBAL.Scheduling.Others;
using PTSMSDAL.Access.Scheduling.Operations;
using System;

namespace PTSMS.Controllers.Scheduling
{
    public class FlightLogsController : Controller
    {
        private ApplicationSignInManager _signInManager;

        private PTSContext db = new PTSContext();

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        AirportLogic airportLogic = new AirportLogic();
        EquipmentLogic equipmentLogic = new EquipmentLogic();

        FlightLogLogic flightLogLogic = new FlightLogLogic();
        ActivityCheckInLogic activityCheckInLogic = new ActivityCheckInLogic();

        // GET: FlightLogs
        public ActionResult Index()
        {
            return View(flightLogLogic.List());
        }

        [HttpGet]
        public PartialViewResult CreateFlightLogPartialView(int flyingFTDScheduleId)
        {
            FlightLog flightLog = new FlightLog();
            FTDAndFlyingSchedulerAccess fTDAndFlyingSchedulerAccess = new FTDAndFlyingSchedulerAccess();
            FlyingFTDSchedule flyingFTDSchedule = fTDAndFlyingSchedulerAccess.Details(flyingFTDScheduleId);
            ViewBag.IsLessonEvaluated = true;

            if (flyingFTDSchedule != null)
            {
                if (flyingFTDSchedule.Status == Enum.GetName(typeof(FlyingFTDScheduleStatus), FlyingFTDScheduleStatus.Evaluated))
                {

                    ActivityCheckIn activityCheckIn = activityCheckInLogic.CheckInDetailsByScheduleId(flyingFTDScheduleId);

                    if (activityCheckIn != null)
                    {
                        flightLog = flightLogLogic.FlightLogDetails(activityCheckIn.ActivityCheckInId);
                        if (flightLog != null)
                            ViewBag.InstrumentApproachId = new SelectList(db.InstrumentApproachs.ToList(), "InstrumentApproachId", "InstrumentApproachName", flightLog.InstrumentApproachId);
                        else
                        {
                            ViewBag.InstrumentApproachId = new SelectList(db.InstrumentApproachs.ToList(), "InstrumentApproachId", "InstrumentApproachName");
                            flightLog = new FlightLog();
                            flightLog.ActivityCheckInId = activityCheckIn.ActivityCheckInId;
                        }
                    }
                    else
                    {
                        ViewBag.InstrumentApproachId = new SelectList(db.InstrumentApproachs.ToList(), "InstrumentApproachId", "InstrumentApproachName");
                    }
                }
                else
                    ViewBag.IsLessonEvaluated = false;
            }
            return PartialView("CreateFlightLogPartialView", flightLog);
        }



        [HttpGet]
        public PartialViewResult FlightLogDetail(int flyingFTDScheduleId)
        {
            FlightLog flightLog = new FlightLog();

            ActivityCheckIn activityCheckIn = activityCheckInLogic.CheckInDetailsByScheduleId(flyingFTDScheduleId);
            if (activityCheckIn != null)
            {
                var flightLogDetial = flightLogLogic.FlightLogDetails(activityCheckIn.ActivityCheckInId);
                if (flightLogDetial != null)
                {
                    flightLog = flightLogDetial;
                    ViewBag.IsFlightLogRegistered = true;
                }
                else
                {
                    ViewBag.IsFlightLogRegistered = false;
                }
            }
            else
            {
                ViewBag.IsFlightLogRegistered = false;
            }
            return PartialView("FlightLogDetail", flightLog);
        }
        // GET: FlightLogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlightLog flightLog = db.FlightLogs.Find(id);
            if (flightLog == null)
            {
                return HttpNotFound();
            }
            return View(flightLog);
        }

        // GET: FlightLogs/Create
        public ActionResult Create()
        {
            ViewBag.ArrivalAirportId = new SelectList(db.Airports, "AirportId", "AirportName");
            ViewBag.DepartureAirportId = new SelectList(db.Airports, "AirportId", "AirportName");
            ViewBag.TailNoId = new SelectList(db.Equipments, "EquipmentId", "NameOrSerialNo");
            ViewBag.EquipmentTypeId = new SelectList(db.EquipmentModels, "EquipmentModelId", "EquipmentModelName");
            ViewBag.FlyingFTDScheduleId = new SelectList(db.FlyingFTDSchedules, "FlyingFTDScheduleId", "Status");
            return View();
        }

        // POST: FlightLogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FlightLog flightLog)
        {
            if (HttpContext.User.Identity.Name != null)
            {
                string password = Request.Form["txtFlightLogPassword"];

                var userValidationResult = SignInManager.PasswordSignInAsync(HttpContext.User.Identity.Name, password, false, shouldLockout: false);

                if (userValidationResult.Result.ToString() == "Success")
                {
                    if (flightLogLogic.Add(flightLog))
                    {
                        TempData["FTDAndFlyingScheduleMessage"] = "Flight log has been saved successfully.";
                    }
                    else
                    {
                        TempData["FTDAndFlyingScheduleMessage"] = "Failed to save flight log.";
                    }
                }
                else
                {
                    TempData["FTDAndFlyingScheduleMessage"] = "Failed to save flight log due to incorrect password.";
                }
            }
            else
            {
                TempData["FTDAndFlyingScheduleMessage"] = "The password you entered is no the password of the current active user.";
            }
            return RedirectToAction("Equipment", "InstructorSchedule", null);
        }
        [HttpPost]
        public JsonResult CreateJson(int ActivityCheckInId, int DayLanding,int DayTakeOff,int FlightLogId,int InstrumentApproachId,int NightLanding,int NightTakeOff, string Remark)
        {
            bool isSuccess = false;
            FlightLog flightLog = new FlightLog();
            flightLog.ActivityCheckInId = ActivityCheckInId;
            flightLog.DayLanding = DayLanding;
            flightLog.DayTakeOff = DayTakeOff;
            flightLog.FlightLogId = FlightLogId;
            flightLog.InstrumentApproachId = InstrumentApproachId;
            flightLog.NightLanding = NightLanding;
            flightLog.NightTakeOff = NightTakeOff;
            flightLog.Remark = Remark;

            if (flightLogLogic.Add(flightLog))
            {
                TempData["FTDAndFlyingScheduleMessage"] = "Flight log has been saved successfully.";
                isSuccess = true;
            }
            else
            {
                TempData["FTDAndFlyingScheduleMessage"] = "Failed to save flight log.";
                isSuccess = false;
            }

            return Json(new { isSuccess = isSuccess, Message = TempData["FTDAndFlyingScheduleMessage"].ToString() }, JsonRequestBehavior.AllowGet);
        }

        // GET: FlightLogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlightLog flightLog = db.FlightLogs.Find(id);
            if (flightLog == null)
            {
                return HttpNotFound();
            }
            ViewBag.InstrumentApproachId = new SelectList(db.InstrumentApproachs.ToList(), "InstrumentApproachId", "InstrumentApproachName", flightLog.InstrumentApproachId);
            return View(flightLog);
        }

        // POST: FlightLogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FlightLog flightLog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(flightLog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(flightLog);
        }

        // GET: FlightLogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlightLog flightLog = db.FlightLogs.Find(id);
            if (flightLog == null)
            {
                return HttpNotFound();
            }
            return View(flightLog);
        }

        // POST: FlightLogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

PTSMS/PTSMS/Views/FlightLogs/CreateFlightLogPartialView.cshtml
@model PTSMSDAL.Models.Scheduling.Relations.FlightLog


@*@using (Html.BeginForm("Create", "FlightLogs", FormMethod.Post, new { enctype = "multipart/form-data", id = "btnFlightLogs" }))
{*@
<div class="col-md-12 hide" id="FlightLogsMessage">
    <div class="row hide" id="FlightLogsMessageSuccess">
        <div class="col-md-12">
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-hand-o-right"></i> Success!</h4>
                <ul>
                    <li><lable id="FlightLogsMessageSuccessLabel"> </lable></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row hide" id="FlightLogsMessageFail">
        <div class="col-md-12">
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-hand-o-right"></i> Failed!</h4>
                <ul>
                    <li><lable id="FlightLogsMessageFailLabel"> </lable></li>
                </ul>
            </div>
        </div>
    </div>
</div>
    <div class="form-horizontal">

        @Html.AntiForgeryToken()

        @{
            if (ViewBag.IsLessonEvaluated != null)
            {
                
                if (ViewBag.IsLessonEvaluated)
                {
                    if (Model.ActivityCheckInId == 0)
                    {
                        <div class="alert alert-warning alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <h4><i class="icon fa fa-warning"></i> Alert!</h4>
                            Sorry, Ramp out didn't made so far.
                        </div>
                    }
                    else
                    {
                        <div class="form-group hide">
                            @Html.LabelFor(model => model.ActivityCheckInId, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.ActivityCheckInId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ActivityCheckInId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group hide">
                            @Html.LabelFor(model => model.FlightLogId, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.FlightLogId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.FlightLogId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DayTakeOff, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.DayTakeOff, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DayTakeOff, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NightTakeOff, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.NightTakeOff, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NightTakeOff, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DayLanding, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.DayLanding, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DayLanding, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NightLanding, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.NightLanding, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NightLanding, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.InstrumentApproachId, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-4">
                                @Html.DropDownList("InstrumentApproachId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.InstrumentApproachId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-4">
                                @Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control", rows = 5 } })
                                @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-group">
                                <lable class="control-label col-md-3">Password: </lable>
                                <div class="col-md-4">
                                    <input type="password" class="form-control" id="txtPassword" name="txtPassword" autocomplete="off" data-val="true" data-val-required="Password is required." />
                                </div>
                            </div>*@
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-4">
                                <input type="submit" value="Create" id="btnFlightLogs" class="btn btn-info" />
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="alert alert-warning alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-warning"></i> Alert!</h4>
                        Sorry, this lesson is not evaluated so far. Recording flight log will be possible right after evaluation. 
                    </div>
                }
            }
        }

       
    </div>

    <div class="form-group hide">
        <input type="text" id="DepartureTimeHours" name="DepartureTimeHour" class="form-control" />
        <input type="text" id="DepartureTimeMinutes" name="DepartureTimeMinutes" class="form-control" />
        <input type="password" name="txtFlightLogPassword" id="txtFlightLogPassword" />
    </div>

@*}*@



@*<link href="~/Content/AdminLTE/plugins/timepicker/bootstrap-timepicker.min.css" rel="stylesheet" />
<link href="~/Content/AdminLTE/plugins/datepicker/datepicker3.css" rel="stylesheet" />

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/validator.js"></script>
<script src="~/Content/AdminLTE/plugins/datepicker/bootstrap-datepicker.js"></script>
<script src="~/Content/AdminLTE/plugins/timepicker/bootstrap-timepicker.min.js"></script>*@


<script type="text/javascript">
    $(document).ready(function () {

        $("#DepartureTime,#ArrivalTime,#TotalFlightTime,#PilotInCommand,#Dual,#FlightTimeDay,#FlightTimeNight,#InstrumentFlightTime,#SyntheticTrainerTime").timepicker({
            showInputs: false,
            showMeridian: false,
            minuteStep: 5
        });

        $('.PTSMSDatepicker').datepicker({
            autoclose: true,
            todayHighlight: true,
            startDate: new Date()
        });
        //DepartureTimeHours,DepartureTimeMinutes
        $('#DepartureTime').timepicker().on('hide.timepicker', function (e) {
            //alert('hide.timepicker');
            $('#DepartureTimeHours').val(e.time.value);
            $('#DepartureTimeMinutes').val(e.time.minutes);
            //alert('The time is ' + e.time.value);
            //alert('The hour is ' + e.time.hours);
            //alert('The minute is ' + e.time.minutes);
            //alert('The meridian is ' + e.time.meridian);
        });
        $('#ArrivalTime').timepicker().on('hide.timepicker', function (e) {
            //alert('hide.timepicker');
            //alert('The time is ' + e.time.value);
            //alert('The hour is ' + e.time.hours);
            //alert('The minute is ' + e.time.minutes);
            //alert('The meridian is ' + e.time.meridian);

            //Get Departure Time
            var depHours = parseInt($('#DepartureTimeHours').val());
            var depMinutes = parseInt($('#DepartureTimeMinutes').val());

            //substruct arrival time from departure time
            var TotalFlightTimeHours = parseInt(e.time.hours) - depHours;
            var TotalFlightTimeMinutes = parseInt(e.time.minutes) - depMinutes;

            if (TotalFlightTimeMinutes < 0) {
                TotalFlightTimeHours = TotalFlightTimeHours - 1;
                TotalFlightTimeMinutes = (60 + TotalFlightTimeMinutes);
            }

            var TotalFlightTime = "";
            if (TotalFlightTimeHours < 10)
                TotalFlightTime = "0" + TotalFlightTimeHours;
            else
                TotalFlightTime = TotalFlightTimeHours;

            if (TotalFlightTimeMinutes < 10)
                TotalFlightTime = TotalFlightTime + ":0" + TotalFlightTimeMinutes;
            else
                TotalFlightTime = TotalFlightTime + ":" + TotalFlightTimeMinutes;

            $('#TotalFlightTime').val(TotalFlightTime);
        });
        $('#btnFlightLogs').on('click', function (e) {
            debugger;
            var data = {
                "ActivityCheckInId": $('#ActivityCheckInId').val(),
                "DayLanding": $('#DayLanding').val(),
                "DayTakeOff": $('#DayTakeOff').val(),
                "FlightLogId": $('#FlightLogId').val(),
                "InstrumentApproachId": $('#InstrumentApproachId').val(),
                "NightLanding": $('#NightLanding').val(),
                "NightTakeOff": $('#NightTakeOff').val(),
                "Remark": $('#Remark').val()
            }

            $.ajax({
                url: "/FlightLogs/CreateJson",
                type: 'POST',
                data: data,
                success: function (result) {
                    $('#FlightLogsMessage').removeClass("hide");
                    if (result.isSuccess) {
                        $('#FlightLogsMessageSuccess').removeClass("hide");
                        $('#FlightLogsMessageFail').addClass("hide");
                        $('#FlightLogsMessageSuccessLabel').html(result.Message);
                    }
                    else {
                        $('#FlightLogsMessageFail').removeClass("hide");
                        $('#FlightLogsMessageSuccess').addClass("hide");
                        $('#FlightLogsMessageFailLabel').html(result.Message);
                    }

                },
                error: function () {
                    $('#FlightLogsMessageFail').removeClass("hide");
                    $('#FlightLogsMessageSuccess').addClass("hide");
                    $('#FlightLogsMessageFailLabel').html("Error has occured while coloring the event.");
                }
            });
        });
    });
</script>

PTSMS/PTSMS/Views/FlightLogs/Delete.cshtml
@model PTSMSDAL.Models.Scheduling.Relations.FlightLog

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FlightLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalAirports.AirportName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArrivalAirports.AirportName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureAirports.AirportName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureAirports.AirportName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Equipment.NameOrSerialNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Equipment.NameOrSerialNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EquipmentModel.EquipmentModelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EquipmentModel.EquipmentModelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlyingFTDSchedule.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlyingFTDSchedule.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArrivalTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PilotInCommand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PilotInCommand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoPilot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoPilot)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dual)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dual)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightEngineerFlightTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightEngineerFlightTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightTimeDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightTimeDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightTimeNight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightTimeNight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InstrumentFlightTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstrumentFlightTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SyntheticTrainerTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SyntheticTrainerTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DayTakeOff)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayTakeOff)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NightTakeOff)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NightTakeOff)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DayLanding)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayLanding)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NightLanding)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NightLanding)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InstrumentApproach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstrumentApproach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PilotFunctionOnBoard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PilotFunctionOnBoard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remark)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PTSMS/PTSMS/Views/FlightLogs/FlightLogDetail.cshtml
@model PTSMSDAL.Models.Scheduling.Relations.FlightLog


@{

    if (ViewBag.IsFlightLogRegistered != null)
    {
        if (ViewBag.IsFlightLogRegistered == true)
        {
            <div>
                <dl class="dl-horizontal">      
                    <dt>
                        @Html.DisplayNameFor(model => model.DayTakeOff)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DayTakeOff)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.NightTakeOff)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NightTakeOff)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DayLanding)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DayLanding)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.NightLanding)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NightLanding)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.InstrumentApproach.InstrumentApproachName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.InstrumentApproach.InstrumentApproachName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Remark)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Remark)
                    </dd>

                </dl>
            </div>
        }
        else
        {
            <div class="">
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-warning"></i> Alert!</h4>
                    <h5>Flight log is not registered for this lesson. Flight log will be visible once your instructor registered it.</h5>
                </div>
            </div>
        }
    }
    else
    {
        <div class="">
            <div class="alert alert-warning alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-warning"></i> Alert!</h4>
                <h5>Flight log is not registered for this lesson. Flight log will be visible once your instructor registered it.</h5>
            </div>
        </div>
    }
}